### ISSUE TITLE
v3.9.0 tag is available on the official Go proxy but not on this repository

### ISSUE THREAD

**Issue by mx-psi** [openshift/api#1661]
The v3.9.0 tag is available on the [pkg.go.dev docs domain](https://pkg.go.dev/github.com/openshift/api@v3.9.0+incompatible) and the official Go proxy (download [here](https://proxy.golang.org/github.com/openshift/api/@v/v3.9.0+incompatible.zip), sumdb entry [here](https://sum.golang.org/lookup/github.com/openshift/api@v3.9.0+incompatible)), but it looks like the tag has been removed from this repository.

This breaks build for anyone that is not using the official Go proxy and is building a module that has v3.9.0 on their dependency tree, it breaks automatic dependency tools like Dependabot and it breaks even people pinning commits if their pseudoversion has 3.9.0 as the base version. **Would it be possible for this tag to be re-added to the repository to avoid this breakage?** Thanks!

Similar issues on other projects for context:
- ionos-cloud/sdk-go/issues/27
- DataDog/agent-payload/issues/218
- go-chi/chi/issues/713

Some related issues for this specific version:
- grafana-operator/grafana-operator/issues/706
- #1421
- #456
- operator-framework/operator-sdk/issues/2394
- openshift/ci-tools/issues/414
- devfile/devworkspace-operator/issues/166
- stackrox/kube-linter/issues/418

As you can see, this causes a lot of pain and has a simple solution: just add the tag back on the same commit it was before.

**Comment by OneCricketeer** [comment]
It was retracted

https://github.com/openshift/api/commit/abb98ff04d03d5d3444b6e49f26c36c0b37e0e03

**Comment by mx-psi** [comment]
@OneCricketeer As the [Go modules reference](https://go.dev/ref/mod#go-mod-file-retract) states:

> Retracted versions should remain available in version control repositories and on [module proxies](https://go.dev/ref/mod#glos-module-proxy) to ensure that builds that depend on them are not broken.

**Comment by mx-psi** [comment]
This is still unsolved and still causing pain. Retracting is not enough and the Go modules reference is very clear that the current status should not happen.
