### ISSUE TITLE
machineconfiguration API protobuf

### ISSUE THREAD

**Issue by runcom** [openshift/api#216]
We're working to move the MCO types from the machine-config-operator repo. Within our types we're using the ignition types https://github.com/openshift/machine-config-operator/blob/master/pkg/apis/machineconfiguration.openshift.io/v1/types.go#L233. We're already doing an  hack to provide DeepCopy https://github.com/openshift/machine-config-operator/blob/master/pkg/apis/machineconfiguration.openshift.io/v1/machineconfig.deepcopy.go but we're now stuck because the Ignition types don't have protobuf annotations (nor the `generate` target writes them ofc). This result in `make generate` working just fine except for the protobuf case because of Ignition. I can see a `$PROTO_OPTIONAL` env but it doesn't seem to take effect.

Do we need to have ingnition types also have protobuf annotation? can we port the api w/o protobuf?

We do have a WIP PR here https://github.com/runcom/api/pull/1 which fails at the bare `make` target because of protobuf as said.

**Comment by derekwaynecarr** [comment]
this impacts the types that embed ignition but not the runtime or kubelet config related types, right?  so we could just move those in the near term, but leave the others non-moved until we get updates for those that embed ignition?

/cc @crawford

**Comment by runcom** [comment]
> this impacts the types that embed ignition but not the runtime or kubelet config related types, right?

As long as they don't reference the MachineConfig type, they should be ok to move (I'll check later today)

> so we could just move those in the near term, but leave the others non-moved until we get updates for those that embed ignition?

not sure what do you mean by "until we get updates for those that embed ignition"? Looks like the general path is to keep ignition around in the machineconfig struct
