### ISSUE TITLE
Route v1 is missing TLSTerminationType enum

### ISSUE THREAD

**Issue by tnozicka** [openshift/api#26]
In openshift/origin we have 

https://github.com/openshift/origin/blame/master/pkg/route/apis/route/types.go#L185-L192

but those are missing in openshift/api

https://github.com/openshift/api/blob/master/route/v1/types.go#L232

**Comment by deads2k** [comment]
They're just missing.  You can open a pull to add them.

**Comment by tnozicka** [comment]
Pull in place https://github.com/openshift/api/pull/28

I wonder how we lost this when it isn't generated and if there can be more place like this one?

**Comment by deads2k** [comment]
> Pull in place #28
> 
> I wonder how we lost this when it isn't generated and if there can be more places like this one?

It just means we only validated after converting to internal.  Adding these here is gravy for people try to use them.

As to staying in sync, I don't have any great ideas.
