### ISSUE TITLE
Client are missing a way to import OpenShift api validations

### ISSUE THREAD

**Issue by tnozicka** [openshift/api#27]
While upstream client has e.g.
```
kvalidation "k8s.io/apimachinery/pkg/api/validation"
kvalidationutil "k8s.io/apimachinery/pkg/util/validation"
```
we don't provide an alternative. Say like a want to validate my route or it's part
https://github.com/tnozicka/origin/blob/4bc612e584a033515ccf468a5206f836814dc49c/pkg/route/apis/route/validation/validation.go#L26
(probably not the best example)

**Comment by deads2k** [comment]
Those validation packages are related to metav1 or generic types.  k8s.io/api doesn't include any validation.  Validation is only performed server-side and is based on internal versions.  We won't be adding validation to our external types for the foreseeable future.
