### ISSUE TITLE
Need API guidelines/standards doc

### ISSUE THREAD

**Issue by bparees** [openshift/api#305]
I'm sure most of it can point to k8s, but we recently had some more generic api-type items come up like the fact that the registry uses port 5000 for its service when it would have been preferred to use :443 so the port suffix is not needed.

I don't know where else the guidelines could go, so including then in an api guidelines doc in this repo seems like as good a place as any.

/cc @smarterclayton @openshift/api-reviewers @adambkaplan

**Comment by dmage** [comment]
We also have a common knowledge that field name references in the godoc must start with lowercase, because it'll be used in the openapi spec. But apparently k8s doesn't follow this recommendation, so it's better to document this difference.
