### ISSUE TITLE
Openshift REST API - /webhooks/ returns wrong selflink (BUILDCONFIG instead of BUILD)

### ISSUE THREAD

**Issue by clemensutschig** [openshift/api#331]
Trigger a pipeline based build thru webhook

curl -k -X POST APIHOST/oapi/v1/namespaces/*NAMESPACE*/buildconfigs/*BUILDCONFIG*/webhooks/*SECRET*/generic

The call returns
"selfLink":"/apis/build.openshift.io/v1/namespaces/*NAMESPACE*/buildconfigs/**BUILDNAME**/instantiate

which imho is wrong - because no new build **config** is created, but rather a **build** ... 
so the selflink should be

/apis/build.openshift.io/v1/namespaces/*NAMESPACE*/builds/*BUILD NAME*

**Comment by soltysh** [comment]
This is not the right repo for this issue, please move this to openshift/origin. /cc @adambkaplan since that's part of your bucket. 
/close
