### ISSUE TITLE
when project is created via api, it is created w/o default role bindinds

### ISSUE THREAD

**Issue by izapolsk** [openshift/api#35]
When I create project using rest api's, it is created w/o default role bindins like system:image-builder,
system:deployer, system:image-puller, etc

**Comment by deads2k** [comment]
Will be fixed by https://github.com/openshift/origin/pull/18795 in origin.  There's a funny coincidence.

**Comment by deads2k** [comment]
> When I create project using rest api's, it is created w/o default role bindins like system:image-builder,
> system:deployer, system:image-puller, etc

Those rolebindings are created as part of the template used when hitting the projectrequest endpoint.  The project endpoint is an ACL filtered view of namespaces, so it won't create additional resources for you.  We expect normal users to use the projectrequest endpoint.

The new controller will be present in 3.10.
