### ISSUE TITLE
ImageStreamTags is missing watch verb

### ISSUE THREAD

**Issue by camilamacedo86** [openshift/api#601]
See that the ImageStreamTags is not implementing the watch which would be important to observe changes in this resource as well. 

```
$ oc api-resources -o wide | grep ImageStream
imagestreamimages                     isimage          image.openshift.io                    true         ImageStreamImage                     [get]
imagestreamimports                                     image.openshift.io                    true         ImageStreamImport                    [create]
imagestreammappings                                    image.openshift.io                    true         ImageStreamMapping                   [create]
imagestreams                          is               image.openshift.io                    true         ImageStream                          [create delete deletecollection get list patch update watch]
imagestreamtags                       istag            image.openshift.io                    true         ImageStreamTag                       [create delete get list patch update]
```

OCP version: 4.3.1

**Comment by camilamacedo86** [comment]
c/c @miguelsorianod

**Comment by soltysh** [comment]
ImageStreamTag as a virtual resource can't provide your that information, so watch is not supported. You should watch a particular ImageStream and get information about the tag you're interested in.

**Comment by smarterclayton** [comment]
With ImageTag we have a potential path to support watch, HOWEVER it is slightly complex to implement and so the investment will be tricky.  It's not that it is impossible, just hasn't hit a certain level of priority.

Note that you should please give ImageTags a try in 4.4 (available in nightlies) which will replace ImageStreamTag for primary use (returns both spec and status).

Let's leave this open and assigned to me for now, I may get back to it.

**Comment by camilamacedo86** [comment]
The problem is that if the WATCH is not implemented then some features, as for example, the watch of the controller-runtime/operator-SDK to observe these resources in order to do operations when some event occurs, I mean when it is changed, cannot be used. Since it was an issue faced by an operator-sdk user (@miguelsorianod) I decided to track it here and in IHMO would be nice have it in all API as possible since the WACTH is used to cache the resources for the client-go as well.
