### ISSUE TITLE
missing loglevel in apiserver.config.openshift.io

### ISSUE THREAD

**Issue by aelicieguo** [openshift/api#614]
According to documentation https://docs.openshift.com/container-platform/4.3/nodes/nodes/nodes-nodes-audit-log.html, there should be loglevel and operatorloglevel in this api CRD.

**Comment by soltysh** [comment]
There's an error in our docs, I fixed it in https://github.com/openshift/openshift-docs/pull/20856. The bit you're looking for is actually in KubeAPIServer or OpenShiftAPIServer types. It's best to verify this using `oc explain openshiftapiserver.spec` or `oc explain kubeapiserver.spec`.
