### ISSUE TITLE
Have the tags been removed recently?

### ISSUE THREAD

**Issue by mkrutov** [openshift/api#647]
Several other issues suggest that there at least used to be tags in this repository, when the tag list is empty now. 

I came here to investigate as to why my go project, which depends on openshift api, started complaining that certain version (mentioned in my go.mod) is not found.

Were the tags completely removed from the repository? Is this an intentional change or an unintentional mistake?

**Comment by michael-bud** [comment]
Is there any update on this?

**Comment by marun** [comment]
@mkrutov This repository doesn't get tagged. If you want to consume with go.mod, you can specify a branch (e.g. master, release-x.x) or SHA to `go get`.

**Comment by mkrutov** [comment]
Ok. I don't recall the exact details which lead me to believe that something has disappeared, unfortunately.
