### ISSUE TITLE
Errors running go mod vendor after pull request #937 merged

### ISSUE THREAD

**Issue by coreydaley** [openshift/api#944]
I am getting all kinds of errors trying to run `go mod vendor` in `openshift/oc` while trying to pull in the commit from pull request #937 , or the one after it.
 - `malformed file path`
 - `invalid char ':'
 
Example:
```
tls/docs/kube-apiserver Serving Certificates/subcert-openshift-kube-apiserver-operator_localhost-recovery-serving-signer@1622133567::2777012960471375622.png: malformed file path "tls/docs/kube-apiserver Serving Certificates/subcert-openshift-kube-apiserver-operator_localhost-recovery-serving-signer@1622133567::2777012960471375622.png": invalid char ':'
```

Can we get this either fixed or reverted?

**Comment by sttts** [comment]
Try https://github.com/golang/go/issues/27642#issuecomment-420711676, i.e. place an empty go.mod file in that dir.
